# 예외

## try-catch-finally문
```
try {
    //시도할 코드들
} catch (<예외 클래스 1>) <변수명>) {
    //예외가 발생할 경우 해당 예외를 처리할 코드
} catch (<예외 클래스 2>) <변수명>) {
    //예외가 발생할 경우 해당 예외를 처리할 코드
} finally {
    //예외가 발생할 경우 해당 예외를 처리할 코드
}
```

## 예외 처리의 Best Practice

1. Finally 블록에서 리소스를 정리하거나, try-with-resources문을 사용

나중에 닫아야 하는 InputStream과같이 try 블록에서 리소스를 사용하는 경우가 많습니다. 이러한 상황에서 일반적인 실수는 try 블록의 끝에 있는 리소스를 닫는 것입니다. 문제는 예외가 throw되지 않는 한 이 접근 방식이 완벽하게 잘 작동하는것 같다는 것입니다. try블록 내의 모든 문이 실행되고 리소스가 닫힙니다. 그러나 당신은 한 이유때문에 try블럭을 추가했습니다.
예외를 throw할 수 있는 하나 이상의 메서드를 호출하거나 예외를 직접 throw할 수도 있습니다. 즉, try블록의 끝에 도달하지 못할 수도 있습니다. 따라서 리소스를 닫지 않습니다. 따라서 모든 클린코드를 finally블록에 넣거나 try-with-resources문을 사용해야합니다.

### Finally 블록 사용

try 블록의 마지막 몇 줄과 는 달리, finally 블록은 항상 실행됩니다. 이는 try 블록의 성공적인 실행 후 또는 캐치 블록에서 예외를 처리한 후에 발생합니다. 따라서 열린 모든 리소스를 정리해야 합니다. 

### 리로스문을 사용한 try문 사용

리소스가 AutoCloseable인터페이스를 구현하는 경우 사용할 수 있습니다. 이것이 대부분의 Java표준 리소스가 하는 일입니다.
try블록에서 리소스를 열면 try블록이 실행되거나 예외가 처리된후 자동으로 닫힙니다.
예시
```
public void automaticallyCloseResource() {
	File file = new File("./tmp.txt");
	try (FileInputStream inputStream = new FileInputStream(file);) {
		// use the inputStream to read a file
		
	} catch (FileNotFoundException e) {
		log.error(e);
	} catch (IOException e) {
		log.error(e);
	}
}
```

2. 특정 예외를 선호합니다.

던지는 예외가 더 구체적일수록 더 좋습니다. 코드를 모르는 동료(또는 몇 개월 안에)가 메서드를 호출하고 예외를 처리해야 할 수 있습니다.

따라서 가능한 한 많은 정보를 제공해야 합니다. 이렇게 하면 API를 더 쉽게 이해할 수 있습니다.

따라서 메서드의 호출자는 예외를 더 잘 처리하거나 추가 확인을 통해 피할수 있습니다.

따라서 항상 뛰어난 이벤트에 가장 적합한 클래스(예: IllegalArgumentException대신 NumberFormatException)를 throw하십시오. 그리고 비구체적인 예외를던지지 마십시오.

```
public void doNotDoThis() throws Exception { ... }
	
public void doThis() throws NumberFormatException { ... }
```

3. 지정한 예외 문서

메서드에 예외를 지정할 때마다 Javadoc에도 문서화해야 합니다.

이는 이전 모범 사례와 동일한 목표를 가지고 있습니다. 호출자가 예외를 피하거나 처리할 수 있도록 가능한 한 많은 정보를 제공합니다.

따라서 Javadoc에 @throws 선언을 추가하고 예외를 일으킬 수 있는 상황을 설명해야 합니다.

```
/**
* This method does something extremely useful ...
*
* @param input
* @throws MyBusinessException if ... happens
*/
public void doSomething(String input) throws MyBusinessException { ... }
 ```

 4. 설명 메시지와 함계 예외를 throw

 이 모범 사례의 이면에 대한 아이디어는 이전 두 가지와 유사합니다. 그러나 이번에는 메서드의 호출자에게 정보를 제공하지 않습니다.

예외의 메시지는 로그 파일 이나 모니터링 도구에 예외가 보고되었을 때 무슨 일이 있었는지 이해해야하는 모든 사람이 읽습니다.

따라서 문제를 가능한 한 정확하게 설명하고 예외적인 이벤트를 이해하기 위해 가장 관련성이 있는 정보를 제공해야 합니다.

나를 잘못 오해하지 마십시오; 텍스트 단락을 작성해서는 안된다. 그러나 1-2 짧은 문장에서 예외의 이유를 설명해야합니다.

이를 통해 운영 팀이 문제의 심각성을 파악할 수 있으며 서비스 인시던트를 보다 쉽게 분석할 수 있습니다.

특정 예외를 throw하면 해당 클래스 이름이 이미 오류 종류를 설명할 가능성이 큽니다. 따라서 많은 추가 정보를 제공할 필요가 없습니다.

그에 대한 좋은 예는 NumberFormatException입니다. 잘못된 형식으로 문자열을 제공하면 클래스 java.lang.Long의 생성자가 throw됩니다.

```
try {
	new Long("xyz");
} catch (NumberFormatException e) {
	log.error(e);
}
```

NumberFormatException 클래스의 이름은 이미 문제의 종류를 알려줍니다. 해당 메시지는 문제를 일으킨 입력 문자열만 제공해야 합니다.

예외 클래스의 이름이 표현력이 없는 경우 메시지에 필요한 정보를 제공해야 합니다.

5. 가장 구체적인 예외를 먼저 catch

대부분의 IDE는 이 모범사례를 도와줍니다. 덜 구체적인 예외를 먼저 잡으려고 할 때 연결할 수 없는 코드 블록을 보고합니다.

문제는 예외와 일치하는 첫 번째 캐치 블록만 실행된다는 것입니다.

따라서 IllegalArgumentException를 먼저 잡으면 IllegalArgumentException의하위 클래스이기 때문에 보다 구체적인 NumberFormat예외를 처리해야 하는 캐치 블록에 도달하지 않습니다.

항상 가장 구체적인 예외 클래스를 먼저 잡고 목록 끝에 덜 구체적인 캐치 블록을 추가합니다.

다음 코드 스니펫(코드 조각)에서 이러한 try-catch 명령문의 예를 볼 수 있습니다. 첫 번째 캐치 블록은 모든 NumberFormatExceptions와 번호가 없는 모든 불법 인수 예외를모두 처리합니다.

```
public void catchMostSpecificExceptionFirst() {
	try {
		doSomething("A message");
	} catch (NumberFormatException e) {
		log.error(e);
	} catch (IllegalArgumentException e) {
		log.error(e)
	}
}
```

6. Throwable을 catch하지 마십시오.
throwwable은 모든 예외 및 오류의 조상 클래스이다. catch절에서 사용할 수 있지만, 절대로 사용해서는 안됩니다. catch 절에서 Throwable를 사용하는 경우 모든 예외를 catch할 뿐만 아니라 또한 모든 오류를 잡을 것입니다. 오류는 JVM이 발생시켜 애플리케이션에 의해 처리되지 않는 심각한 문제를 나타냅니다.

따라서 오류를 처리할 수 있거나 필요한 예외적인 상황에 처해 있다고 절대적으로 확신하지 않는 한 Throwable을 잡을 수 없습니다.

```
public void doNotCatchThrowable() {
	try {
		// do something
	} catch (Throwable t) {
		// don't do this!
	}
}
```
7.
8.
9.


## 참고 
https://stackify.com/best-practices-exceptions-java/